### ISSUE TITLE
Allow to use one sprite from different styles

### ISSUE THREAD

**Issue by ai** [hagenburger/lemonade#10]
We have a big styles (our design is a maniac) and I split it to separated files (header.sass, footer.sass, etc) and join it in production by jammit. Lemonade is very useful and I try to add images from header and footer to one sprite. But sprite image will contain only images from last one style file.

As I understand problem is when you compile sprite in `Compass::Compiler#compile` for every sass file and `Lemonade.generate_sprites` clean `$lemonade_sprites` after each call.

**Comment by ai** [comment]
Now I just import other files to application.sass, but it is only temporal decision.

**Comment by ai** [comment]
I think in `Sass::Tree::RootNode#render` we need to call somethink like `Lemonade.mark_as_saved` (instead of `Lemonade.reset`), where we didn’t clear `@@sprites`, but we are mark all sprites as saved. On new `sprite_url` we mark sprite as unsaved and in `Lemonade.generate_sprites` save only unsaved sprites.
I try to write this code in next week.

**Comment by dreamerslab** [comment]
I'm having the same problem, is there a way to fix it?

**Comment by ai** [comment]
Yes, use beta of compass with build-in sprites support.

**Comment by dreamerslab** [comment]
Thanks a lot :)
But I found it is harder to use with compass.
I have to split "sprite-image" into "sprite-map" and "sprite".
And in sprite-map function I have to specify each spacing( and other args too ) with each file name as a prefix.
at the end I went back with the stable version.

**Comment by hagenburger** [comment]
I’m closing this because of [some deprecation](https://github.com/hagenburger/lemonade#readme).
