### ISSUE TITLE
Undefined variable "$repeat"

### ISSUE THREAD

**Issue by ai** [hagenburger/lemonade#11]
I install latest lemonade (`gem install lemonade --pre`), but on `+sprite-image("layout/logo.png")` it throw error:

```
Syntax error: Undefined variable: "$repeat".
        on line 7 of /home/ai/.gem/ruby/1.8/gems/lemonade-1.0.0.beta.1/lib/../stylesheets/lemonade.scss, in `sprite-image'
        from line 36 of /home/ai/project/app/styles/./_top.sass
        from line 47 of /home/ai/project/app/styles/application.sass
```

**Comment by ai** [comment]
Pull request http://github.com/hagenburger/lemonade/pull/13

**Comment by hagenburger** [comment]
I’m closing this because of [some deprecation](https://github.com/hagenburger/lemonade#readme).
