### ISSUE TITLE
Another path to images dir

### ISSUE THREAD

**Issue by ai** [hagenburger/lemonade#12]
Sometimes we need to save web page to dir, so in out project we use relative paths to images (`../images/file.png`). In `compass.config` I set `http_images_path = "../images"`, but Lemonade didn’t use `http_images_path` (`background: url('/images/layout.png?1286392056') 0 -15px`) :(.

I use 1.0.0.beta.1 version.

**Comment by ai** [comment]
Ok, I understand, that I need to use `Lemonade.images_path` but it wasn’t so easy :).

**Comment by ai** [comment]
I have Rails project with Compass.

**Comment by hagenburger** [comment]
I’m closing this because of [some deprecation](https://github.com/hagenburger/lemonade#readme).
