### ISSUE TITLE
Different URL for one sprite

### ISSUE THREAD

**Issue by ai** [hagenburger/lemonade#14]
SASS insert timestamp to images in styles. But when I add lemonade, I load one sprite image 4 times, because they have different timestamp: `/images/layout.png?1286396880`, `/images/layout.png?1286396881`, `/images/layout.png?1286396882`, `/images/layout.png?1286396883`. This image uses in several SASS-file, which I import to one (_footer.sass, _header.sass and _top.sass import to application.sass).

**Comment by ai** [comment]
Compass use modify time, but as I understand sprite changes several times. So we can use `Compass.configuration.asset_cache_buster` proc, to set `Time.now` (calculated once in compilation).

**Comment by thijsc** [comment]
+1

**Comment by roytomeij** [comment]
This is quite a big issue: creating sprites now only is a disadvantage. Instead of downloading 20 small icons, the browser now needs to download a large sprite 20 times.

**Comment by ai** [comment]
Put this to `config/compass.config`:

```
asset_cache_buster do |http_path, real_path|
  if http_path =~ /images\/([^\/]+)\.png/
    Pathname.glob(Rails.root.join(images_dir).join($1).join('*.png')).
      map { |i| i.mtime }.max.to_i.to_s
  else
    File.mtime(real_path).to_i.to_s
  end
end
```

**Comment by roytomeij** [comment]
Thanks. Seems to fix it for the time being. Would still need something more solid I guess ;-)

**Comment by hagenburger** [comment]
I’m closing this because of [some deprecation](https://github.com/hagenburger/lemonade#readme).
