### ISSUE TITLE
Add repeat-x functionality

### ISSUE THREAD

**Issue by johnf** [hagenburger/lemonade#15]
Add a repeat argument to sprite-image. If true then the resulting image will be copied into the sprite multiple times to fill it's width.

This is isueful or when your sprite has multiple images of different widths and you want to repeat-x a 1 pixel wide image.

**Comment by johnf** [comment]
Closing this as a bug was opened when I created the pull request

**Comment by hagenburger** [comment]
This will be available in Compass Sprites, I finished it yesterday: http://github.com/chriseppstein/compass/commit/702452275ee24863bf102800bf7928bd18f58e22
