### ISSUE TITLE
Use only one png file

### ISSUE THREAD

**Issue by rafudu** [hagenburger/lemonade#18]
Why does Lemonade uses the images directory name for the sprite? "/logo/large.png" -> logo.png. "/menu/corner.png" -> menu.png

Is there a way for me to combine all the sprites inside an application.png file?

thanks!

**Comment by hagenburger** [comment]
Yes, you should not combine small images (like icons) with large ones (like layout things) as it would result in large file sizes (at least in the browser memory) which would be bad for performance. If you wand to combine them, you have to put them into the same directory.

**Comment by rafudu** [comment]
yeah, that is true. but I was thinking: what if the name generation use the top directory, instead of the lower?

example:
- /application/logo/footer.png -> application.png
- /application/menu/corner.png -> application.png
- /icons/16x16/ok.png -> icons.png
- /icons/32x32/cancel.png -> icons.png

I think this is better than generating logo, menu, 16x16 and 32x32 sprites. Mostly because I organize my files in folders, like logo, menu,icons, buttons, loaders. But not necessarily they should be different sprites. Defining the sprites using the top-most directory may give Lemonade more flexibility and also allow the developer to organize the files in his own manner.

Maybe this could be a configuration option?

thanks!
