### ISSUE TITLE
Relative Assets

### ISSUE THREAD

**Issue by iammerrick** [hagenburger/lemonade#19]
Fails when relative_assets = true. Image is generated beautifully but the url is incorrect.

**Comment by rizkysyazuli** [comment]
I'm having the same problem.. why use absolute path anyway?? it should be turned off by default..

on my mac. the site path is inside the user "Sites" folder. my local urls is something like: "localhost/~username/projectname". absolute paths fails miserably..

edit: setting `relative_assets = true` seems fixes the problem. but in textmate i usually just drag n drop files to the window and it guesses the correct path. now with lemonade, i have to re-adjust those path before lemonade works properly. imho, let user decide the image path in their css. don't append the `images_dir` config from compass to the compiled css.

just saying.. :)

**Comment by hagenburger** [comment]
I’m closing this because of [some deprecation](https://github.com/hagenburger/lemonade#readme).
