### ISSUE TITLE
Cannot get Lemonade to work

### ISSUE THREAD

**Issue by lmartins** [hagenburger/lemonade#2]
Installed both ImageMagick and RMagic on Snow Leopard, installed Lemonade but still when i try to use the syntax i still get no conversion on the generated css. Any suggestions for what i may have missed?

**Comment by hagenburger** [comment]
Did you add `require "lemonade"` to config.rb (sometimes named compass.config or compass.rb)?

**Comment by lmartins** [comment]
Yes, i did require the plugin to load in config.rb but still no luck.
All i get on the output is something like:
.sprite {
  background: sprite-img("../images/temp/sprite02.jpg");
}

**Comment by hagenburger** [comment]
Did you mean `sprite-image(...)`?

**Comment by lmartins** [comment]
oh boy, quite embarrassed right now....  ;-)

**Comment by hagenburger** [comment]
http://github.com/hagenburger/lemonade/commit/9a654b1c658740adf7e81f39a824792d6e1b32cf

Only for you :)
