### ISSUE TITLE
Lemonade.reset in Sass::Tree::RootNode.render

### ISSUE THREAD

**Issue by steve-wong** [hagenburger/lemonade#21]
line 12 in lib/lemonade/sass_extension.rb calls Lemonade.reset

With that line, I only get a single image in the generated sprite image file even though I'm using the sprite-image sass function in multiple places.  However, if I remove that line, then the generated sprite has all the images as expected.  Is the Lemonade.reset suppose to be there?  Do I have something else misconfigured?

**Comment by hagenburger** [comment]
I’m closing this because of [some deprecation](https://github.com/hagenburger/lemonade#readme).
