### ISSUE TITLE
configuration possibilites and delete mode?

### ISSUE THREAD

**Issue by codefreeze** [hagenburger/lemonade#23]
Hey,
why does sass --watch realize that i delete an scss file and delete the generated css file, too, but your compass +lemonade only compile, but never delete css files if the scss file is missing?
Also ist will be cool if genrated sprites will be deleted too

And second question:
How can i configurate a spezial output path for generated sprites? for my deployment process its not really a good way to have the generated sprites in the same directory hirachy as my source files.

/dir1/dir2/file1.png
/dir1/dir2/file2.png

generates

/dir1/dir2.png

my wish is that i could say, put all sprites to :

/images/sprites

I think its a good work, but i don't feel free in use..

**Comment by hagenburger** [comment]
I’m closing this because of [some deprecation](https://github.com/hagenburger/lemonade#readme).
