### ISSUE TITLE
Lemonade fails when running compass compile

### ISSUE THREAD

**Issue by jgyllen** [hagenburger/lemonade#25]
I'm trying to compile Sass stylesheets using the Compass command line tool and I get the following error:
<code>NoMethodError on line ["69"] of /Users/baron/.rvm/gems/ruby-1.9.2-p136@sl-profiles/gems/lemonade-1.0.0.beta.1/lib/lemonade.rb: undefined method `to_yaml' for #Hash:0x0000010126de08</code>

I have added <code>require "lemonade"</code> to the Compass config file.

Any clues?

**Comment by hagenburger** [comment]
I also had this issue. You can solve it by using [bundler](http://gembundler.com/).

```
# Gemfile
source 'http://rubygems.org'
gem 'activesupport', '3.0.3' # if it won’t work, try an older version
gem 'compass', '0.10.6'
gem 'lemonade', '1.0.0.beta.1'
```

Run `bundle` and change your Compass config:

```
 require 'bundler'
 Bundler.setup
 require "lemonade"
```

By the way: I recommend to use the latest Compass alpha version which includes Lemonade. Have a look at the [new documentation](http://beta.compass-style.org/help/tutorials/spriting/).

**Comment by jgyllen** [comment]
Thanks! That worked. :)

And thanks for the tip about the alpha version.

Cheers.
