### ISSUE TITLE
Lemonade dismiss some sprites when used in multiple files

### ISSUE THREAD

**Issue by RodolpheGohard** [hagenburger/lemonade#28]
Hello,

I use lemonade a lot in my project, currently in 3 separated scss files. Not always but sometimes, Lemonade would only generate the spriteset for one file.

say I have :
**_file1.scss**_
    .userIcon {
        background: sprite-image("../images/icons/user.png");
    }
    .interfaceIcon {
        background: sprite-image("../images/icons/interface.png");
    }
    .serverIcon {
        background: sprite-image("../images/icons/server.png");
    }

**_file2.scss**_
        .add {
            background: sprite-image("../images/icons/veilleB_add.png");
            @include button-21x21;  
        }
        .del {
            background: sprite-image("../images/icons/veilleB_suppr.png");
            @include button-21x21;
        }

**_file3.scss**_
       #basesToolbar {
    .searchIcon{
            background: sprite-image("../images/icons/rechercheB.png");
            @include button-21x21;
    }

```
.add {
        background: sprite-image("../images/icons/baseB_add.png");
        @include button-21x21;          
}
.del {
        background: sprite-image("../images/icons/baseB_suppr.png");
        @include button-21x21;
}
   }
```

Sometimes the generated spriteset would only contain:
-"../images/icons/user.png",
-"../images/icons/interface.png" and 
-"../images/icons/server.png" 
which are defined in file1, sometimes in only the images from file2 , and sometimes all is ok ...

I still didn't get how to reproduce this bug surely. What I do to avoid it when it comes to happen is forcing the regenaration of sprites by indicating a wrong path in sprite-image calls and correcting them again.

I think I can workaround this issue by storing all sprite-image calls results to scss variables in one single file.

**Comment by hagenburger** [comment]
I’m closing this because of [some deprecation](https://github.com/hagenburger/lemonade#readme).
