### ISSUE TITLE
Generated sprite is an empty png

### ISSUE THREAD

**Issue by daytonn** [hagenburger/lemonade#29]
Lemonade seems to be generating a sprite without errors but the sprite is just an empty png.

**Comment by hagenburger** [comment]
Could you please provide more details/code/project …

**Comment by daytonn** [comment]
I'm using compass 0.10.6 in a non-rails project. My config:

<pre>
# Require any additional compass plugins here.
require "lemonade"
# Set this to the root of your project when deployed:
http_path = "/"
css_dir = "css"
sass_dir = "scss"
images_dir = "images"
javascripts_dir = "js"
sass_options = { :debug_info => true }
# To enable relative paths to assets via compass helper functions. Uncomment:
#relative_assets = true
output_style = :compact
</pre>


The code in question:

<pre>
a.sprite-class {
     background: sprite-image("icons/some-small.png");
}

a.another-sprite-class {
     background: sprite-image("icons/some-other-small.png");
}
</pre>


When compiled there are no errors, and there is an icons.png generated in the images directory, however the icons.png is blank. I tried moving the source images into the images directory and then received a not found error so I have reason to believe it is finding the source images.

**Comment by stereobooster** [comment]
I have same problem. windows 7, ruby-1.9.2-p136-i386-mingw32, lemonade-0.3.4
I can provide my images

**Comment by stereobooster** [comment]
duplicte of https://github.com/hagenburger/lemonade/issues/closed#issue/30

**Comment by daytonn** [comment]
@stereobooster Yeah, it was marked closed right after I posted it citing no code provided. I created a new one and added the requested code. Apparently this issue is not a priority because it keeps getting marked as closed. I would say it's a pretty serious issue since the "fix" is downgrading a gem.
