### ISSUE TITLE
Horizontal padding

### ISSUE THREAD

**Issue by lmartins** [hagenburger/lemonade#3]
This is not a bug but a feature request. It would be nice to have the option for adding horizontal padding  to the generated sprites. 

Thanks for the great plugin! :-)

**Comment by hagenburger** [comment]
You’re welcome :)

How should this look like? Is this another feature than:

```
sprite-image("some/image.png", 12px)
```

**Comment by lmartins** [comment]
If i understand it correctly, that would adjust the background position only, my goal was to add horizontal spacing on the generated image, much like the vertical spacing that Lemonade already creates.

**Comment by hagenburger** [comment]
Can you give me an example, where to use it?

**Comment by lmartins** [comment]
The most common case for me is in situations where my container is bigger that the sprite-image. This can easily be tackled by making the original image with empty space around it, but i think it would be nice to have that option directly on Lemonade.

**Comment by hagenburger** [comment]
Sounds a bit like `background: sprite-image("...") no-repeat` could help ...
