### ISSUE TITLE
Undefined mixin 'sprite-image'.

### ISSUE THREAD

**Issue by ghost** [hagenburger/lemonade#31]
-Added require "lemonade" to config.rb
-Added this to my Sass file..

a.twitter
    background: sprite-image("/images/twitter.png")

-Getting this..
Syntax error: Undefined mixin 'sprite-image'.

**Comment by hagenburger** [comment]
Is this the whole code of your Sass file?

**Comment by hagenburger** [comment]
I’m closing this because of [some deprecation](https://github.com/hagenburger/lemonade#readme).
