### ISSUE TITLE
only empty (transparent) sprite images are being created

### ISSUE THREAD

**Issue by brunopinho** [hagenburger/lemonade#32]
When I use 'background: sprite-image("images/tester/image1.png") no-repeat;' a 'tester.png' is created, but completely empty... 
Is this a known issue? Am I doing anything wrong?

Thanks!

**Comment by Luwe** [comment]
Just use the spriting options in the new version of Compass (0.11): http://compass-style.org/reference/compass/helpers/sprites/ The new Compass has Lemonade built inside.

Lemonade has this issue when working with newer versions of the chunky_png gem (v1.0 and up I think).

**Comment by brunopinho** [comment]
@Luwe
Thanks a lot for the tip... ;)

Cheers!
