### ISSUE TITLE
Mark lemonade as obsolete

### ISSUE THREAD

**Issue by thijsc** [hagenburger/lemonade#34]
I heard from a friend that started using Lemonade last week, based on a tip I gave him 6 months ago. He hadn't noticed that Lemonade is now part of Compass.

It would probably be a good idea to put this in big letters at the top of README?

**Comment by hagenburger** [comment]
YES.

Cheers 

Nico

Nico Hagenburger // www.hagenburger.net // www.twitter.com/hagenburger

Am 29.05.2011 um 13:59 schrieb thijsc:

**Comment by hagenburger** [comment]
done.

https://github.com/hagenburger/lemonade/commit/c1c28988d97361de40a6a3ebe1640f64a033e9c5
https://github.com/hagenburger/lemonade
http://www.hagenburger.net/BLOG/Lemonade-CSS-Sprites-for-Sass-Compass.html
http://rubygems.org/gems/lemonade
