### ISSUE TITLE
Would you please consider to rename lemonade gem on rubygems.org?

### ISSUE THREAD

**Issue by wartin** [hagenburger/lemonade#36]
Yeah, this was a great project and it is still has a great usage within Compass.

But once it is deprecated for about 2 years, would you consider to rename gem to something like `lemonade-sprites` or `lemonade-legacy`.

This way you'll let people bring new Lemonade flavors to Ruby world :)

Cheers.

**Comment by hagenburger** [comment]
Thanks, but there is no reason to do that right now.
