### ISSUE TITLE
dark border around png sprites

### ISSUE THREAD

**Issue by lmartins** [hagenburger/lemonade#5]
Im having an issue with PNG sprites. The generated sprites always haves a dark stroke around the image, where it was supposed to be a soft shadow. Im on OSX. Any suggestions?

**Comment by hagenburger** [comment]
Could you please send me the original and generated image? Thanks.

**Comment by lmartins** [comment]
Sure, where can i send them?

**Comment by hagenburger** [comment]
Bug was already fixed in 0.3.2.
