### ISSUE TITLE
'images.png' was not found (or cannot be read)

### ISSUE THREAD

**Issue by peeper** [hagenburger/lemonade#7]
Hi, i have a problem with Lemonade.

OS: Windows 7, Ruby: 1.9.1

My config.rb is:

css_dir = "css"
sass_dir = "sass"
line_comments = false
require "lemonade"

When i run "compass watch", the console shows:

> > > Change detected to: C:/XXX/sass/styles.scss
> > > WARNING: 'images.png' was not found (or cannot be read) in C:/XXX/images/..
> > > ChunkyPNG::SignatureMismatch on line ["102"] of C: PNG signature not found!
> > > Run with --trace to see the full backtrace

Styles.scss have:

h1{
    width: 194px;
    height: 54px;
    background: #FFF sprite-image("../images/bg_logo.gif") no-repeat left top;
    margin: 5px 0 0 20px;
}

Any idea?

Thanks

**Comment by peeper** [comment]
The problem is with the gif. Lemonade only works with .png,
Regards

**Comment by hagenburger** [comment]
closed
