### ISSUE TITLE
Images not created / Chunky_png error

### ISSUE THREAD

**Issue by jdeerhake** [hagenburger/lemonade#8]
Whenever I run compass watch, the CSS is created fine but the sprites are not.  
It spits out this error: 
    NoMethodError on line 40 of /home/jdeerhake/.rvm/gems/ree-1.8.7-2010.02/gems/chunky_png-0.9.0/lib/chunky_png/image.rb: "undefined method `metadata=' for #ChunkyPNG::Canvas:0x1ca4260"
chunky_png v0.9.0 is installed, i tried it with v0.8.0 too to no avail.

I know you recently merged into compass but I was hoping to use this in production fairly soon and am hoping not to wait for the next release.

**Comment by hagenburger** [comment]
Could you please add your compass.config, the Sass/SCSS code where this happens and the lemonade version?

Thanks.

**Comment by jdeerhake** [comment]
Thanks for the quick reply.  I am using lemonade 0.3.4.
My entire scss file right now is just this:
    body { background: sprite-image("home/bg_leaderboard.png"); }
my config/compass.rb (i'm on rails) is:
    # This configuration file works with both the Compass command line tool and within Rails.
    # Require any additional compass plugins here.
    require "lemonade"
    project_type = :rails
    project_path = Compass::AppIntegration::Rails.root
    # Set this to the root of your project when deployed:
    http_path = "/"
    css_dir = "public/stylesheets"
    sass_dir = "app/stylesheets"
    environment = Compass::AppIntegration::Rails.env
    # To enable relative paths to assets via compass helper functions. Uncomment:
    # relative_assets = true

also for what it's worth - ruby 1.8.7 and rails 2.3.8.

**Comment by jdeerhake** [comment]
Strangely this doesn't seem to be happening 100% of the time, but around 90% or so.

I can't seem to figure out whats causing it to work occasionally. I've tried using different source images but I've had successes and failures on the same images.

**Comment by hagenburger** [comment]
I still could not reproduce it. Maybe you can try to use the current beta (`gem install lemonade --pre`)—but the beta won’t be released as of the merge with compass.

**Comment by jdeerhake** [comment]
Ok thanks for your help.

One last question - does lemonade (or maybe compass?) keep a cache anywhere?

I think this may have been a problem with an image I had that is now cached or something. Because I continue to get the error now even if I completely empty out the scss stylesheet.

**Comment by jdeerhake** [comment]
Actually, after working on this with a friend for awhile, we've determined it to be a bug within chunky_png not lemonade.

Thanks for the help.
