### ISSUE TITLE
relative parents path are dusturbing Lemonade

### ISSUE THREAD

**Issue by RodolpheGohard** [hagenburger/lemonade#9]
Hello,

here're my scss rules:
.status-ok {
    background: sprite-image("../images/icons/ok.png");
}
.status-ko {
    background: sprite-image("../images/icons/ko.png");
}

the spritesset is correctly generated at ../images/icons.png , but the css generated rules points uncorrectly like this:
url("/../images/../images/icons.png") repeat scroll 0 -16px transparent

so there's a trailing /../images/ that comes from nowhere which makes all bugging.

Am I missing something or have we a bug ?

**Comment by hagenburger** [comment]
I didn’t intend to use this with relative paths, as the locations are defined by Compass (it uses the image_url() function to output the url()). I think it’s a lucky break that the image is generated as you expected it ;)

It should generate a warning if you use relative paths—I don’t think it’s good to use relative paths for the spriting.

**Comment by RodolpheGohard** [comment]
I have a differents directories for images and css, so I can only use parents path to reach them. And I can't mess up all my directory structure just to fix that up.

Is there a way to configure Compass to lookup for images in the right directory so I can avoid using parented paths?

**Comment by hagenburger** [comment]
Of course, you are able to use different locations for CSS and images.

Please set http_images_path, images_dir, sass_dir and css_dir in the Compass configuration. You’ll find more information in the [Compass documentation](http://compass-style.org/docs/tutorials/configuration-reference/).

**Comment by heygrady** [comment]
That totally worked. I had the same issue, glad I checked here. This tripped me up for about 35 minutes. It should probably be on the manual page under gotchas.

http_path = ""
css_dir = "css"
sass_dir = "src"
images_dir = "i"
javascripts_dir = "js"
http_images_path = "../i"
